### PR TITLE
Support application base override

### PR DESCRIPTION
**Pull request by d3m3vilurr**
inspired from touchegg
`override app_class[,...]` will override gesture configurations.

example: https://gist.github.com/d3m3vilurr/b6af4052acc2b88bf2f5e28305217632

it's quick&dirty patch.

### CODE REVIEW

**Comment by bulletmark** [comment]
Apart from being a bit "dirty" as you say, this change does not support Wayland which many of us are already using and which we are all moving to. Sorry but I would also implement this differently.

**Comment by d3m3vilurr** [comment]
huh... does not work xlib methods in the wayland environ?
dirty means I wasn't cleanup xlib import parts & current_config_groups looks mess.
anyway okay, i'll wait your implements :)

**Comment by bulletmark** [comment]
It will probably work for X clients running in Wayland environment, but it won't work for native Wayland clients.

**Comment by d3m3vilurr** [comment]
ah, got it. thx.

**Pull request closed without merging**
