### PR TITLE
Fedora 25 doesn't ship with wmctrl

### PR DESCRIPTION
**Pull request by jbtrystram**
I needed to install it in order to have the gestures working again :)

### CODE REVIEW

**Comment by bulletmark** [comment]
The README says you should install `xdotool` and `wmctrl` and gives example package install lines for both Arch Linux and Debian based systems. I didn't want to list explicit instructions for every variation of Linux package management systems out there. Stating that those 2 packages are required is enough.

**Comment by bulletmark** [comment]
BTW, Arch and Debian/Ubuntu don't ship with `wmctrl` or `xdotool` either. The user is expected to read the instructions and install those required packages. Of course, Arch users can install from the AUR which takes care of dependencies.

**Comment by jbtrystram** [comment]
Oh yeah that make sense, sorry for missing that. 
I upgraded from fedora 24 to 25 and needed to install that package, hence this PR.

**Comment by bulletmark** [comment]
I don't see why you had to install `wmctrl` when you upgraded to Fedora 25? Version 2.9 of this `libinput-gestures` changed the default swipe commands from `xdotool` to an `_internal` command which is based on `wmctrl` so that is the point at which you would have had to install `wmctl`, if you were using the default config file. It has nothing to do with Fedora. It must be that at a similar time, you also upgraded this utility.

**Pull request closed without merging**
