### PR TITLE
Icons Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
Just a redesign to make it less archaic and "janky".

### CODE REVIEW

**Comment by bulletmark** [comment]
Thanks very much. ;)

**Comment by bulletmark** [comment]
Actually, after merging your PR I started thinking about this more and realise that libinput-gestures should not really appear as an application because it is not intended to be started manually. Users start, stop, and set it to autostart via the `libinput-gestures-setup` shell script. So I intend to delete the png and your svg file and will mark the desktop file as "NoDisplay". Any reason you don't agree with this?

**Comment by Fatih20** [comment]
You should get rid of the desktop shortcut icon entirely instead. Picture below doesn't look good, even worse if it doesn't have any icon at all.
Screenshot from 2020-04-04 08-29-02

**Comment by bulletmark** [comment]
That's what I am saying. It will not appear at all in the GNOME overview. Actually I will keep the svg file because it just occurred to me that people will see it on their list of startup apps, e.g. in GNOME tweaks. That is the only place it will be seen.

**Comment by bulletmark** [comment]
I pushed the above change with commit cd2df31992833ed1f63fe2763a5393a258dad5f8.

**Comment by Fatih20** [comment]
Ok that's nice.

**Pull request merged**
