### PR TITLE
application dependent command execution

### PR DESCRIPTION
**Pull request by swissiety**
Hello,
i wanted to execute different commands depending on which application was active at the moment of the gesture (like touchegg did? - never got it to work). If the gesture for the active application is not configured, then it looks for the respective gesture in a catchall section (section name defaults to 'general'). Maybe the modification is useful for others, too.

### CODE REVIEW

**Comment by gschaffner** [comment]
If you're still looking for a way to accomplish this, you might consider calling an external script when a gesture is triggered: check out https://ubuntuforums.org/showthread.php?t=380927.

Also, #37 and #69 are related.

**Comment by TimurSarbassov** [comment]
Is it possible to configure this utility, so it makes possible to move to previous/next folder in the file manager by swiping left/right?

**Comment by shivanshs9** [comment]
I implemented this functionality in my [forked library](https://github.com/shivanshs9/power-gestures/). You can give it a try if you'd like to use it.

**Comment by bulletmark** [comment]
This is not something I would consider merging sorry. Seems like it only works with X applications anyhow. Anybody interested in this functionality should go to the forked repo.

**Pull request closed without merging**
