### PR TITLE
ACL through udev

### PR DESCRIPTION
**Pull request by m1st0**
Added ACL uacess option using udev on Ubuntu 18.10.  I can possibly add systemd changes later if desired.

### CODE REVIEW

**Comment by bulletmark** [comment]
Sorry, way more complicated than the simple one-liner `gpasswd` command. If I merged this I would spent forever here dealing with issues debugging user's broken udev rules.

**Comment by m1st0** [comment]
Since it isn't replacing the original process but offering an alternative
if desired, would it still be something you don't want to merge even if I
likely would be the one to deal with that area from time to time?

**Comment by bulletmark** [comment]
Sorry, I just don't think using a udev rule is worthwhile for anybody.

**Comment by m1st0** [comment]
Understandable, thanks

**Pull request closed without merging**
