### PR TITLE
Add setgid wrapper

### PR DESCRIPTION
**Pull request by mhoeher**
These changes add an additional setgid wrapper to the gesture handler. The idea is to get rid of the requirement of adding users manually to the `input` group:

* The previous `libinput-gestures` script has been renamed to `libinput-gestures.py`.
* A new file `libinput-gestures.c` has been added, which ensures that the Python process executing the `libinput-gestures.py` file runs with the C wrapper's effective user and group ID.
* During installation, the wrapper is compiled on the fly. The resulting binary is set to be owned by the `input` group. Additionally, the `setgid` bit is set on the executable.

This approach makes it easier to package the scripts, as interested users no longer need to add themselves to the `input` group.

### CODE REVIEW

**Comment by 0-kaladin** [comment]
make install with this PR gives:
```
libinput-gestures.c: In function ‘main’:
libinput-gestures.c:26:25: warning: too many arguments for format [-Wformat-extra-args]
     sprintf(scriptPath, "%s.py", exePath, PATH_MAX);
```

**Comment by mhoeher** [comment]
Hi @0-kaladin,

thanks for the hint. I switched to use `snprintf` and fixed the argument list. I retried with the `format-extra-args` warning enabled (also with `-Wall`) and the wrapper compiles fine without warnings (at least here, I am using Fedora 25).

**Comment by bulletmark** [comment]
I am sorry but I don't want to add this extra complexity and the requirement to compile C code just to avoid the one-liner installation instruction. We also lose the ability to run the code directly from the repo for testing, etc.

BTW, from a quick look-over of your code. I would probably just do a `dirname()` of `argv[0]` to get the path of the corresponding `.py` program. Also, you should indent stuff you add within an if statement of the `libinput-gestures-setup`. It is convention to do a `make` (as user) to compile the code, then a `make install` (as root/sudo) to install it.

**Comment by mhoeher** [comment]
Hi @bulletmark,

I understand your point regarding complexity of the build and - yes - with the patch as it is implemented right now, you cannot test as easy locally as before. Are you generally declined to the setgid approach or would you think a fully optional solution would be okay? The point is that I recently packaged libinput-gestures and I think from an end user point of view it is much better if you do not require this additional setup step (especially as uninstalling really means uninstalling the package afterwards - group membership seldom is undone at software removal).

Regarding your other points:
- Indentation: You are fully right. This is due to the file seems to use tabs but my editor is set to use spaces only for indentation. My fault.
- Using "make && make install": True, makes a lot of sense.

**Comment by bulletmark** [comment]
I don't really like having to require a user to manually add themselves to a system group either but I still greatly prefer it to hacking around the problem with a setuid/setgid wrapper given the many other disadvantages that approach adds.

**Pull request closed without merging**
