### PR TITLE
Continuous gestures

### PR DESCRIPTION
**Pull request by askmyhat**
Added gesture smooth-pinch for continuous actions like zoom

### CODE REVIEW

**Comment by cunidev** [comment]
Still no news?

**Comment by bulletmark** [comment]
@cunidev is that a question and who is it addressed to?

**Comment by GammaGames** [comment]
@bulletmark I think they were wondering if it was going to be merged, or if there was something else blocking approval

**Comment by bulletmark** [comment]
@GammaGames well @cunidev never answered so we don't really know what he was asking.

The PR code only supports the one type of gesture the author was wanting and also I would not be happy to merge that code as is.

**Comment by cunidev** [comment]
Apologies, I apparently didn't receive/ignore the email notification and missed that. That's what I meant anyway.

**Comment by GammaGames** [comment]
I think the smooth pinch in and out are probably the most useful continuous gestures, though I can see why you wouldn't want to merge just those. Thank you!

**Pull request closed without merging**
