### PR TITLE
Libinput Extended features

### PR DESCRIPTION
**Pull request by shivanshs9**
Since this update diverges a lot from the intended path of libinput-gestures, I wasn't sure whether to actually open a PR. But, then I felt that I won't be contributing anything at all if I am hesitant about sharing my new ideas for this wonderful utility.

Well, as mentioned in the updated README, the old configuration file format had to be dropped to make way for an extensible configuration to do just _amazing_ things with one's touchpad and maybe few keystrokes.

Hope it is a positive contribution to the growth of libinput-gestures.

### CODE REVIEW

**Comment by bulletmark** [comment]
This is a very different application with incompatible config file. I suggest your rename it and maintain it independently.

Sorry, but I want to keep `libinput-gestures` simple and lightweight.

**Comment by shivanshs9** [comment]
Yeah, I understand. I'll be maintaining the derivative work of libinput-gestures, then.
Will have to think up of a new name then. :weary: 
Anyways, thanks!

**Comment by piegamesde** [comment]
@shivanshs9 Would it be possible to build your tool on top of libinput-gestures? As a configuration wrapper, this would remove the need of having two code bases doing essentially the same and you wouldn't bother merging in changes from here.

**Comment by shivanshs9** [comment]
Hmm... This script won't work as a wrapper. Maybe I can make this script backwards-compatible, by also supporting the older configuration format with original features.
Since the base framework had to be changed to support extensible features, I just can't build on top of the original script.

**Pull request closed without merging**
